name: Build and Push All Services

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 654654229415.dkr.ecr.ap-south-1.amazonaws.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Services
        run: |
          services=("frontend" "cartservice" "productcatalogservice" "checkoutservice" "paymentservice" "shippingservice" "emailservice" "recommendationservice" "currencyservice")

          for service in "${services[@]}"; do
            echo "Processing $service"

            aws ecr describe-repositories --repository-names $service || \
            aws ecr create-repository --repository-name $service

            cd app/src/$service

            docker build -t $service .

            docker tag $service:latest $ECR_REGISTRY/$service:latest

            docker push $ECR_REGISTRY/$service:latest

            cd -
          done