- name: Build and Push Services
  run: |
    services=("frontend" "cartservice" "productcatalogservice" "checkoutservice" "paymentservice" "shippingservice" "emailservice" "recommendationservice" "currencyservice")

    for service in "${services[@]}"; do
      echo "Processing $service"

      if [ -f "app/src/$service/Dockerfile" ]; then
        echo "Dockerfile found for $service"

        aws ecr describe-repositories --repository-names $service || \
        aws ecr create-repository --repository-name $service

        cd app/src/$service

        docker build -t $service .

        docker tag $service:latest $ECR_REGISTRY/$service:latest

        docker push $ECR_REGISTRY/$service:latest

        cd -
      else
        echo "Skipping $service (no Dockerfile found)"
      fi
    done